name: azfunctions-dockerhub-aks-keda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/functionappcontagem
  CAMINHO_PROJETO_FUNCTIONAPP: ./FunctionAppContagem
  CAMINHO_YAML_DEPLOYMENT: ./FunctionAppContagem/deployment-keda.yml
  AZURE_RESOURCE_GROUP_K8S: TesteKubernetes
  AZURE_CLUSTER_K8S: AKSCluster
  
jobs:

  build-dockerhub:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Build de imagem
      run: |
        cd ${{ env.CAMINHO_PROJETO_FUNCTIONAPP }}
        ls
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER

    - name: Login no Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker push --all-tags ${{ env.IMAGEM_DOCKERHUB }}


  deployment-aks:
    needs: [build-dockerhub]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Azure Kubernetes Service - set context - Conectando ao cluster
      uses: Azure/aks-set-context@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        resource-group: ${{ env.AZURE_RESOURCE_GROUP_K8S }}
        cluster-name:  ${{ env.AZURE_CLUSTER_K8S }}

    - name: Instalar Azure Functions Core Tools v3
      run: npm i azure-functions-core-tools@3

    - name: Testar instalação - Azure Functions Core Tools v3
      run: npx func
      
    - name: Gerar YAML para Deployment da Function App
      run: |
        docker pull ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        cd ${{ env.CAMINHO_PROJETO_FUNCTIONAPP }}
        npx func kubernetes deploy --name functionappcontagem --image-name ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER --namespace ingress-nginx --dry-run > deployment-keda.yml

    - name: Exibir conteúdo com o YAML para Deployment da Function App
      run: |
        cd ${{ env.CAMINHO_PROJETO_FUNCTIONAPP }}
        cat deployment-keda.yml

    - name: Upload do YAML para Deployment como Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: deployment-keda
        path: ${{ env.CAMINHO_YAML_DEPLOYMENT }}
        retention-days: 30

    - name: Kubernetes - Deployment da Function App no AKS
      run: kubectl apply -f ${{ env.CAMINHO_YAML_DEPLOYMENT }} --namespace ingress-nginx
